apiVersion: v1
kind: Service
metadata:
  name: nats-external
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
