apiVersion: v1
kind: Service
metadata:
  name: local-nats-external
spec:
  type: ClusterIP
  externalIPs:
  - 170.64.206.253 
  selector:
    app: nats-local 
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222