apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJicmFiZWVtIiwicGFzc3dvcmQiOiJkY2tyX3BhdF82VmdtY1NiT3dHYkNSaTRKYlZVNlYwU1k5REkiLCJhdXRoIjoiWW5KaFltVmxiVHBrWTJ0eVgzQmhkRjgyVm1kdFkxTmlUM2RIWWtOU2FUUktZbFpWTmxZd1UxazVSRWs9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
