auth:
  enabled: true
  password: "password"
  sentinel: true

master:
  count: 1
  persistence:
    enabled: false

replica:
  replicaCount: 3
  persistence:
    enabled: false

sentinel:
  enabled: true
  masterSet: "mymaster"
  quorum: 2